export const GET_HOME_SLIDERS = "GET_HOME_SLIDERS";
export const GET_HOME_CATEGORIES = "GET_HOME_CATEGORIES";
export const GET_HOME_BRANDS = "GET_HOME_BRANDS";
export const GET_HOME_TOP_PRODUCTS = "GET_HOME_TOP_PRODUCTS";
export const GET_HOME_SETTINGS = "GET_HOME_SETTINGS";
